### ISSUE TITLE
Original z85 specification does not allow partial frames

### ISSUE THREAD

**Issue by ribasushi** [noseglid/base85#7]
Unlike the Ascii85 specification, z85 [explicitly prohibits](https://github.com/zeromq/rfc/blob/master/spec_32.txt#L39) encoding of [non-%4](https://github.com/zeromq/rfc/blob/master/src/spec_32.c#L75-L77) or decoding of [non-%5](https://github.com/zeromq/rfc/blob/master/src/spec_32.c#L110-L112) inputs. While your approach of supporting this anyway is reasonable, this should probably be mentioned in the documentation under "possible interoperability issues" or somesuch.

Alternatively you could simply add a z85_strict encoding scheme, which would DTRT.

Cheers

**Comment by noseglid** [comment]
Thanks for bringing this to my attention. I think it should be enforced under the `z85` encoding scheme since this cannot be considered anything else than a bug.

I'd accept a PR for this.

**Comment by ribasushi** [comment]
At this time I am not able to submit a patch - I actually don't know the language well enough to do a "confident one-off PR" nor do I use the library. I was simply doing research into various *85 implementations and came across your stuff.

No sweat either way, just wanted to let you know early on that this is more of a "PSA" than a "I need this fixed" ;)

**Comment by noseglid** [comment]
I was not referring to you specifically. Just letting anyone know who might be interested that I'm all in favor for this! Thanks for taking the time to write your findings here!
